isDataAvailableForKey should be public to easier to check data available
parse-community/Parse-SDK-iOS-OSX pull request #1595
Opened 2021-01-18 08:56 UTC by kennic

… so you don't need to fetch all data to get a certain data.
Sometimes the data of a user is very long but we just need to get the "username" which is already fetched.
This PR also avoid crashing when we try to get data from key which is not fetched. It should returns nil.

So we could check or get data by either ways:
```
if user.isDataAvailable(forKey: "username") {
 // ok
}
```
or
```
if let username = user["username"] {
// username is available
}
else {
// username is unavailable, please fetch it
}
```

2021-01-27 15:34 UTC, stephanboner requested changes
Looks good to me in general but why did you include the change in ParseUI into this PR? Is this on purpose?

2021-01-27 16:14 UTC, kennic commented
> Looks good to me in general but why did you include the change in ParseUI into this PR? Is this on purpose?

It's on purpose, it's just a minor fix to silent the "variable not used" warning

2021-01-27 17:15 UTC, stephanboner approved these changes
Well then it looks good to me

2021-11-21 17:33 UTC, dielsonsales commented on ParseUI/Classes/SignUpViewController/PFSignUpView.m
> -        currentY = CGRectGetMaxY(frame);
Why is this being kept commented though?

2023-10-07 13:44 UTC, dplewis commented
@mtrezza What do you want to do with this?

2023-10-24 13:14 UTC, mtrezza commented
Closing a superseded by #1756

2023-10-24 13:14 UTC, closed without merging