Update Facebook SDK dependency to latest version 17.x and remove ParseFacebookUtilsTvOS
parse-community/Parse-SDK-iOS-OSX pull request #1776
Opened 2024-04-05 05:37 UTC by chriscborg

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1775).

### Issue Description
This aims to resolve a compatibility issue with Xcode 15.3 and the Facebook SDK, bumping Facebook SDK version to 17.x. This Pull Request forks from an existing PR https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1774. Credits to [matteolongeri-ovolab](https://github.com/matteolongeri-ovolab).

Closes: #1775
Closes: #1773
Closes: #1764

### Approach
Updated Swift package to update the Facebook SDK to latest version which resolves this compatibility issue.

### To Do before merging
- [ ] Update documentation specifying that ParseFacebookUtilsTvOS has been removed.

### Credits
[matteolongeri-ovolab](https://github.com/matteolongeri-ovolab) for Pull Request #1774

2024-04-05 08:14 UTC, chriscborg commented
After performing this upgrade, when logging in using `PFFacebookUtils.logInInBackground`, I'm getting an error 101 from Parse "Facebook auth is invalid for this user". Not sure how to resolve this one though. Any ideas please?

2024-04-05 14:52 UTC, mtrezza approved these changes

2024-04-06 18:57 UTC, mtrezza requested changes
This PR requires a rebase. Also, how about removing the FacebookUtils altogether?

2024-04-08 09:31 UTC, mtrezza commented
Closing via https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1779

2024-04-08 09:32 UTC, closed without merging